name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  BUILD_TYPE: Debug
  TARGET: install
  SANDBOX_TEST: True

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install CMake 4.0
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v4.0.0/cmake-4.0.0-linux-x86_64.sh
          sudo mkdir -p /opt/cmake
          sudo sh cmake-4.0.0-linux-x86_64.sh --skip-license --prefix=/opt/cmake
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
          cmake --version

      - name: build and install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DSANDBOX_TEST=${{env.CSMUNIT_TEST}}
          sudo cmake --build build --target ${{env.TARGET}}
          rm -rf build

      - name: configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSANDBOX_TEST=${{env.CSMUNIT_TEST}}

      - name: build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
